# Generated by Django 5.1.7 on 2025-03-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Address',
        ),
    ]
