# Generated by Django 5.1.7 on 2025-03-25 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_remove_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.address'),
        ),
    ]
