# Generated by Django 5.1.7 on 2025-03-26 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Address',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.address'),
        ),
    ]
