# Generated by Django 5.1.7 on 2025-05-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payement_method',
            new_name='payment_method',
        ),
    ]
