# Generated by Django 5.1.7 on 2025-05-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_rename_payement_method_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='chargily_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
