# Generated by Django 5.1.7 on 2025-04-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_rental', '0003_alter_rental_return_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='customer',
            new_name='user',
        ),
        migrations.AddField(
            model_name='rental',
            name='payement_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cib', 'CIB'), ('edahabia', 'Edahabia')], default='cash', max_length=10),
        ),
    ]
