# Generated by Django 5.1.7 on 2025-04-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_rental', '0004_rename_customer_rental_user_rental_payement_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pc',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pc',
            name='is_available',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
