# Generated by Django 5.1.7 on 2025-04-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_rental', '0005_alter_pc_brand_alter_pc_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='image',
            field=models.ImageField(upload_to='pc_images/'),
        ),
    ]
