# Generated by Django 5.1.7 on 2025-04-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_rental', '0006_alter_pc_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='RentalRequest',
        ),
    ]
