# Generated by Django 5.1.7 on 2025-04-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_rental', '0007_rental_status_alter_rental_rental_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='aviability_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
