# Generated by Django 5.1.7 on 2025-04-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_rental', '0009_remove_rental_status_alter_rental_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='payement_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cib', 'CIB'), ('edahabia', 'Edahabia')], max_length=10),
        ),
    ]
