# Generated by Django 5.1.7 on 2025-04-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_rental', '0011_alter_rental_rental_date_alter_rental_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='aviability_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, help_text='Rental price per day in USD', max_digits=10),
        ),
    ]
