# Generated by Django 5.1.7 on 2025-04-30 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_rental', '0012_alter_pc_aviability_date_alter_pc_price_per_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='payement_method',
            new_name='payment_method',
        ),
    ]
